/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainClass */

#ifndef _Included_MainClass
#define _Included_MainClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainClass
 * Method:    energyProduction
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_MainClass_energyProduction
  (JNIEnv *, jclass, jint);

/*
 * Class:     MainClass
 * Method:    turnOn
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MainClass_turnOn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     MainClass
 * Method:    isOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MainClass_isOn
  (JNIEnv *, jclass, jint);

/*
 * Class:     MainClass
 * Method:    error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MainClass_error
  (JNIEnv *, jclass);

/*
 * Class:     MainClass
 * Method:    max
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_MainClass_max
  (JNIEnv *, jclass, jint);

/*
 * Class:     MainClass
 * Method:    min
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_MainClass_min
  (JNIEnv *, jclass, jint);

/*
 * Class:     MainClass
 * Method:    mean
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_MainClass_mean
  (JNIEnv *, jclass, jint);

/*
 * Class:     MainClass
 * Method:    latitude
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MainClass_latitude
  (JNIEnv *, jclass);

/*
 * Class:     MainClass
 * Method:    longitude
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MainClass_longitude
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
