/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pt_fct_is_work2_DeviceEmulator */

#ifndef _Included_pt_fct_is_work2_DeviceEmulator
#define _Included_pt_fct_is_work2_DeviceEmulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    energyProduction
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_pt_fct_is_work2_DeviceEmulator_energyProduction
  (JNIEnv *, jclass, jint device_id);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    turnOn
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pt_fct_is_work2_DeviceEmulator_turnOn
  (JNIEnv *, jclass, jint _state, jint device_id);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    isOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pt_fct_is_work2_DeviceEmulator_isOn
  (JNIEnv *, jclass, jint device_id);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pt_fct_is_work2_DeviceEmulator_error
  (JNIEnv *, jclass);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    max
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_pt_fct_is_work2_DeviceEmulator_max
  (JNIEnv *, jclass, jint device_id);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    min
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_pt_fct_is_work2_DeviceEmulator_min
  (JNIEnv *, jclass, jint device_id);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    mean
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_pt_fct_is_work2_DeviceEmulator_mean
  (JNIEnv *, jclass, jint device_id);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    latitude
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pt_fct_is_work2_DeviceEmulator_latitude
  (JNIEnv *, jclass);

/*
 * Class:     pt_fct_is_work2_DeviceEmulator
 * Method:    longitude
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pt_fct_is_work2_DeviceEmulator_longitude
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
